import { JobCard } from '../../models/job-card.model';

export const jobCardList: JobCard[] = [
  {
    title: 'РАБОТНИК НА ФЕРМУ',
    subtitle: 'Сельское хозяйство и садовничество',
    tags: ['Сельхозрабочий /Работник на ферму'],
    requirements: 'Требования: Срочно на ферму с коровами Lapy (недалеко от Bialostoka)требуются мужчина работник для выполнения несложных обязанностей по кормлению и уборке на ферме с коровами и бычками. Желательно умение ездить на тракторе, но не обязательно. Оплата 3000 злотых в месяц плюс бесплатное питание и проживание.Своевременная оплата,хорошая хозяйка.',
    employer: {
      paymentPerHour: '20',
      paymentPerMonth: '200 – 1000',
      employerName: 'SNK Group sp. z o.o.',
      employerAddress: 'Познань',
      employerLogoSource: '../../../assets/images/job-card/employer-logo.png',
    },
    conditions: [
      {title: 'Постоянная работа', conditionType: 'employment', required: true, },
      {title: 'Не требуется знание языка', conditionType: 'language', required: true, },
      {title: 'Предоставляем питание', conditionType: 'eat', required: true, },
      {title: 'Предоставляем жилье', conditionType: 'housing', required: true, },
      {title: 'Только с рабочей визой', conditionType: 'international-passport', required: true, },
      {title: 'Не требуется опыт', conditionType: 'experience', required: true, },
    ],
    gender: ['male'],
  },
  {
    title: 'РАБОТНИК НА FBR',
    subtitle: 'Сельское хозяйство и садовничество',
    tags: ['Сельхозрабочий /Работник на ферму'],
    requirements: 'Требования: Срочно на ферму с коровами Lapy (недалеко от Bialostoka)требуются мужчина работник для выполнения несложных обязанностей по кормлению и уборке на ферме с коровами и бычками. Желательно умение ездить на тракторе, но не обязательно. Оплата 3000 злотых в месяц плюс бесплатное питание и проживание.Своевременная оплата,хорошая хозяйка.',
    employer: {
      paymentPerHour: '666',
      paymentPerMonth: '2200 – 4000',
      employerName: 'SNK Group sp. z o.o.',
      employerAddress: 'Познань',
      employerLogoSource: '../../../assets/images/job-card/employer-logo.png',
    },
    conditions: [
      {title: 'Постоянная работа', conditionType: 'employment', required: true, },
      {title: 'Не требуется знание языка', conditionType: 'language', required: true, },
      {title: 'Предоставляем питание', conditionType: 'eat', required: true, },
      {title: 'Предоставляем жилье', conditionType: 'housing', required: true, },
      {title: 'Только с рабочей визой', conditionType: 'international-passport', required: true, },
      {title: 'Не требуется опыт', conditionType: 'experience', required: true, },
    ],
    gender: ['male'],
  },
  {
    title: 'РАБОТНИК НА КИТАЙ',
    subtitle: 'Сельское хозяйство и садовничество',
    tags: ['Сельхозрабочий /Работник на ферму'],
    requirements: 'Требования: Срочно на ферму с коровами Lapy (недалеко от Bialostoka)требуются мужчина работник для выполнения несложных обязанностей по кормлению и уборке на ферме с коровами и бычками. Желательно умение ездить на тракторе, но не обязательно. Оплата 3000 злотых в месяц плюс бесплатное питание и проживание.Своевременная оплата,хорошая хозяйка.',
    employer: {
      paymentPerHour: '99',
      paymentPerMonth: '4300 – 8500',
      employerName: 'SNK Group sp. z o.o.',
      employerAddress: 'Познань',
      employerLogoSource: '../../../assets/images/job-card/employer-logo.png',
    },
    conditions: [
      {title: 'Постоянная работа', conditionType: 'employment', required: true, },
      {title: 'Не требуется знание языка', conditionType: 'language', required: false, },
      {title: 'Предоставляем питание', conditionType: 'eat', required: true, },
      {title: 'Предоставляем жилье', conditionType: 'housing', required: true, },
      {title: 'Только с рабочей визой', conditionType: 'international-passport', required: true, },
      {title: 'Не требуется опыт', conditionType: 'experience', required: true, },
    ],
    gender: ['male'],
  },
  {
    title: 'РАБОТНИК НА КГБ',
    subtitle: 'Сельское хозяйство и садовничество',
    tags: ['Сельхозрабочий /Работник на ферму'],
    requirements: 'Требования: Срочно на ферму с коровами Lapy (недалеко от Bialostoka)требуются мужчина работник для выполнения несложных обязанностей по кормлению и уборке на ферме с коровами и бычками. Желательно умение ездить на тракторе, но не обязательно. Оплата 3000 злотых в месяц плюс бесплатное питание и проживание.Своевременная оплата,хорошая хозяйка.',
    employer: {
      paymentPerHour: '777',
      paymentPerMonth: '6700 – 8900',
      employerName: 'SNK Group sp. z o.o.1111111 фывфв',
      employerAddress: 'Познань',
      employerLogoSource: '../../../assets/images/job-card/employer-logo.png',
    },
    conditions: [
      {title: 'Постоянная работа', conditionType: 'employment', required: true, },
      {title: 'Не требуется знание языка', conditionType: 'language', required: false, },
      {title: 'Предоставляем питание', conditionType: 'eat', required: true, },
      {title: 'Предоставляем жилье', conditionType: 'housing', required: true, },
      {title: 'Только с рабочей визой', conditionType: 'international-passport', required: true, },
      {title: 'Не требуется опыт', conditionType: 'experience', required: true, },
    ],
    gender: ['male'],
  },
];
